# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fermentadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('sensorId', models.CharField(max_length=10)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('fermentadorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempcontrol.Fermentadores')),
            ],
        ),
        migrations.CreateModel(
            name='Temperaturas_historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fermentador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempcontrol.Fermentadores')),
                ('sensorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempcontrol.Sensores')),
            ],
        ),
    ]
