# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fermentadores',
            name='sensorId',
        ),
    ]
