# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0004_auto_20160207_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlprocesos',
            name='fermentador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempcontrol.Fermentadores', to_field='nombre'),
        ),
        migrations.AlterField(
            model_name='fermentadores',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='temperaturas',
            field=models.CommaSeparatedIntegerField(max_length=9),
        ),
    ]
