# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0006_auto_20160207_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='fermentadorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempcontrol.Fermentadores', verbose_name='Fermentador'),
        ),
        migrations.AlterField(
            model_name='temperaturashistorial',
            name='fermentador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempcontrol.Fermentadores', verbose_name='Fermentador'),
        ),
        migrations.AlterField(
            model_name='temperaturashistorial',
            name='sensorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempcontrol.Sensores', verbose_name='sensor'),
        ),
    ]
