# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0007_auto_20160207_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensores',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fermentadores',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
