# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0008_auto_20160207_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlprocesos',
            options={'ordering': ['coccion_num'], 'verbose_name_plural': 'Control de Procesos'},
        ),
        migrations.AlterModelOptions(
            name='fermentadores',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Fermentadores'},
        ),
        migrations.AlterModelOptions(
            name='sensores',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Sensores'},
        ),
        migrations.AlterModelOptions(
            name='temperaturashistorial',
            options={'ordering': ['fermentador'], 'verbose_name_plural': 'Historial de Temperaturas'},
        ),
        migrations.AlterModelOptions(
            name='temperaturasperfiles',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Perfiles de Temperatura'},
        ),
    ]
