# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0009_auto_20160207_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlprocesos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
