# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0011_auto_20160207_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturasperfiles',
            name='clarificadoFin',
        ),
        migrations.RemoveField(
            model_name='temperaturasperfiles',
            name='fermentacion1Fin',
        ),
        migrations.RemoveField(
            model_name='temperaturasperfiles',
            name='fermentacion2Fin',
        ),
        migrations.RemoveField(
            model_name='temperaturasperfiles',
            name='maduracionFin',
        ),
        migrations.AddField(
            model_name='temperaturasperfiles',
            name='diasFermentado1',
            field=models.IntegerField(null=True, verbose_name='días 1er fermentado'),
        ),
        migrations.AddField(
            model_name='temperaturasperfiles',
            name='diasFermentado2',
            field=models.IntegerField(null=True, verbose_name='días 2da fermentado'),
        ),
        migrations.AddField(
            model_name='temperaturasperfiles',
            name='diasMadurado',
            field=models.IntegerField(null=True, verbose_name='días madurado'),
        ),
        migrations.AddField(
            model_name='temperaturasperfiles',
            name='diasclarificado',
            field=models.IntegerField(null=True, verbose_name='días clarificado'),
        ),
    ]
