# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0012_auto_20160207_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlprocesos',
            options={'ordering': ['coccionNum'], 'verbose_name_plural': 'Control de Procesos'},
        ),
        migrations.RemoveField(
            model_name='controlprocesos',
            name='coccion_num',
        ),
        migrations.AddField(
            model_name='controlprocesos',
            name='clarificadoFin',
            field=models.DateField(blank=True, null=True, verbose_name='Final Clarificado'),
        ),
        migrations.AddField(
            model_name='controlprocesos',
            name='coccionNum',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Numero de cocción'),
        ),
        migrations.AddField(
            model_name='controlprocesos',
            name='fermentado1Fin',
            field=models.DateField(blank=True, null=True, verbose_name='Final 1er Fermentado'),
        ),
        migrations.AddField(
            model_name='controlprocesos',
            name='fermentado2Fin',
            field=models.DateField(blank=True, null=True, verbose_name='Final 2da Fermentado'),
        ),
        migrations.AddField(
            model_name='controlprocesos',
            name='maduradoFin',
            field=models.DateField(blank=True, null=True, verbose_name='Final Madurado'),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='diasFermentado2',
            field=models.IntegerField(null=True, verbose_name='días 2do fermentado'),
        ),
    ]
