# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0013_auto_20160207_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlprocesos',
            name='clarificadoFin',
            field=models.DateField(verbose_name='Final Clarificado'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='coccionNum',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Nro. de cocción'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='fermentado1Fin',
            field=models.DateField(verbose_name='Final 1er Fermentado'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='fermentado2Fin',
            field=models.DateField(verbose_name='Final 2da Fermentado'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='maduradoFin',
            field=models.DateField(verbose_name='Final Madurado'),
        ),
        migrations.AlterField(
            model_name='temperaturashistorial',
            name='fechaSensado',
            field=models.DateField(verbose_name='fecha de sensado'),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='diasFermentado1',
            field=models.IntegerField(verbose_name='días 1er fermentado'),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='diasFermentado2',
            field=models.IntegerField(default='0', verbose_name='días 2do fermentado'),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='diasMadurado',
            field=models.IntegerField(verbose_name='días madurado'),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='diasclarificado',
            field=models.IntegerField(verbose_name='días clarificado'),
        ),
    ]
