# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 02:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0015_temperaturashistorial_coccionnumero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlprocesos',
            name='clarificadoFin',
            field=models.DateField(verbose_name='Clarificado'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='coccionNum',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Nro. cocción'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='fechaInicio',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 2, 8, 23, 52, 24, 211509), null=True, verbose_name='Inicio de proceso'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='fermentado1Fin',
            field=models.DateField(verbose_name='Fermentado 1'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='fermentado2Fin',
            field=models.DateField(verbose_name='Fermentado 2'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='maduradoFin',
            field=models.DateField(verbose_name='Madurado'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='temperaturaPerfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempcontrol.TemperaturasPerfiles', verbose_name='Perf. Temperatura'),
        ),
    ]
