# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 03:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0016_auto_20160208_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlprocesos',
            name='fechaInicio',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 2, 9, 0, 25, 3, 536563), null=True, verbose_name='Inicio de proceso'),
        ),
    ]
