# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0017_auto_20160209_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensores',
            name='fermentador',
        ),
        migrations.AddField(
            model_name='fermentadores',
            name='sensor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tempcontrol.Sensores'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio de proceso'),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='diasFermentado1',
            field=models.IntegerField(verbose_name='días 1er Fermentado'),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='diasFermentado2',
            field=models.IntegerField(default='0', verbose_name='días 2do Fermentado'),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='diasMadurado',
            field=models.IntegerField(verbose_name='días Madurado'),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='diasclarificado',
            field=models.IntegerField(verbose_name='días Clarificado'),
        ),
    ]
