# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 21:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0020_auto_20160210_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlprocesos',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='clarificadoFin',
            field=models.DateTimeField(verbose_name='Clarificado'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='coccionNum',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(1)], verbose_name='Nro. cocción'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='fermentado1Fin',
            field=models.DateTimeField(verbose_name='Fermentado 1'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='fermentado2Fin',
            field=models.DateTimeField(verbose_name='Fermentado 2'),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='maduradoFin',
            field=models.DateTimeField(verbose_name='Madurado'),
        ),
        migrations.AlterField(
            model_name='fermentadores',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempcontrol.Sensores'),
        ),
        migrations.AlterField(
            model_name='temperaturashistorial',
            name='coccionNumero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempcontrol.ControlProcesos'),
        ),
        migrations.AlterField(
            model_name='temperaturashistorial',
            name='fechaSensado',
            field=models.DateTimeField(verbose_name='fecha de sensado'),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='diasFermentado1',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='días 1er Fermentado'),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='diasFermentado2',
            field=models.IntegerField(default='0', validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='días 2do Fermentado'),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='diasMadurado',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='días Madurado'),
        ),
        migrations.AlterField(
            model_name='temperaturasperfiles',
            name='diasclarificado',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='días Clarificado'),
        ),
    ]
