# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0021_auto_20160210_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturashistorial',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
