# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0022_auto_20160213_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlprocesos',
            name='fase',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
