# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0023_auto_20160213_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlprocesos',
            options={'ordering': ['fermentador'], 'verbose_name_plural': 'Control de Procesos'},
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='fase',
            field=models.CharField(default='fermentacion1', max_length=15),
        ),
    ]
