# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0024_auto_20160213_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturashistorial',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
