# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 15:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0027_auto_20160213_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentadores',
            name='arduinoId',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='Identificador en Arduino'),
        ),
    ]
