# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0029_auto_20160215_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturashistorial',
            name='coccionNumero',
        ),
        migrations.AddField(
            model_name='temperaturashistorial',
            name='coccionNum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tempcontrol.ControlProcesos'),
        ),
    ]
