# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempcontrol', '0031_auto_20160221_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturasperfiles',
            name='temperaturasClarificado',
            field=models.CommaSeparatedIntegerField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='temperaturasperfiles',
            name='temperaturasFermentado1',
            field=models.CommaSeparatedIntegerField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='temperaturasperfiles',
            name='temperaturasFermentado2',
            field=models.CommaSeparatedIntegerField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='temperaturasperfiles',
            name='temperaturasFinalizado',
            field=models.CommaSeparatedIntegerField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='temperaturasperfiles',
            name='temperaturasMadurado',
            field=models.CommaSeparatedIntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='controlprocesos',
            name='fase',
            field=models.CharField(default='fermentado1', max_length=15),
        ),
        migrations.AlterField(
            model_name='temperaturashistorial',
            name='coccionNumero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempcontrol.ControlProcesos'),
        ),
    ]
